### PR TITLE
build fix in linux gcc

### PR DESCRIPTION
**Pull request by sunjin-choi**

### CODE REVIEW

**Comment by elamdf** [comment]
can you just change the type of the cache sizes to be `size_t`? technically this will produce undefined/incorrect behavior for very large cache sizes

**Comment by sunjin-choi** [comment]
ah sure

**Comment by elamdf** [comment]
ah I meant change the underlying member variable type- this still has the same issue as before, just on the opposite variable. Generally we want to avoid `static_cast`s unless we are sure they're safe (because, for example, we have some information that the compiler doesn't)

**Comment by elamdf** [comment]
LGTM!

**Pull request merged**
